---
# TODO: package.json is missing in the installed files so we need to find another way to check the version
- name: Uninstall outdated codam-web-greeter
  tags: [codam.webgreeter, codam.webgreeter.install]
  become: true
  shell:
    cmd: "[[ v$(cat /usr/share/web-greeter/themes/codam/package.json | jq -r '.version') == {{ codam_web_greeter_version }} ]] || rm -rf /usr/share/web-greeter/themes/codam"
    executable: /bin/bash
    removes: "/usr/share/web-greeter/themes/codam" # do not run if codam theme folder does not exist

- name: Create codam-web-greeter theme directory
  tags: [codam.webgreeter, codam.webgreeter.install]
  become: true
  file:
    path: /usr/share/web-greeter/themes/codam
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Clone codam-web-greeter git
  tags: [codam.webgreeter, codam.webgreeter.install]
  git:
    repo: "{{ codam_web_greeter_git_repo }}"
    dest: /tmp/codam-web-greeter
    version: "{{ codam_web_greeter_version }}"
    force: true

- name: Set data-server-url
  tags: [codam.webgreeter, codam.webgreeter.install]
  lineinfile:
    path: /tmp/codam-web-greeter/static/settings.ini
    line: "data-server-url={{ codam_web_greeter_data_server_url }}"
    state: present
    regexp: '^data-server-url='

- name: Build codam-web-greeter
  tags: [codam.webgreeter, codam.webgreeter.install]
  make:
    chdir: /tmp/codam-web-greeter
    target: build

- name: Install codam-web-greeter
  tags: [codam.webgreeter, codam.webgreeter.install]
  become: true
  make:
    chdir: /tmp/codam-web-greeter
    target: install

- name: Fetch initial codam-web-greeter data.json from server
  tags: [codam.webgreeter, codam.webgreeter.install]
  service:
    daemon_reload: true
    name: codam-web-greeter
    state: started
  failed_when: false
